import { Product, User, Order, Invoice, Client } from '@/types';

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Flap Bag',
    brand: 'Chanel',
    description: 'Timeless elegance meets modern sophistication. This iconic quilted lambskin bag features the signature interlocking CC clasp and chain strap.',
    price: 8500,
    images: ['/images/products/chanel-flap.jpg'],
    category: 'Shoulder Bags',
    condition: 'Like New',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Speedy 30 Monogram',
    brand: 'Louis Vuitton',
    description: 'The iconic Louis Vuitton Speedy in classic monogram canvas. Perfect for everyday elegance.',
    price: 1450,
    salePrice: 1250,
    images: ['/images/products/lv-speedy.jpg'],
    category: 'Handbags',
    condition: 'Excellent',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Birkin 35',
    brand: 'Hermes',
    description: 'The ultimate status symbol. This stunning Birkin in Togo leather features palladium hardware.',
    price: 15000,
    images: ['/images/products/hermes-birkin.jpg'],
    category: 'Handbags',
    condition: 'New',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Lady Dior Medium',
    brand: 'Dior',
    description: 'Elegant cannage-stitched lambskin with silver hardware and DIOR charms.',
    price: 5200,
    images: ['/images/products/dior-lady.jpg'],
    category: 'Handbags',
    condition: 'Like New',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Gucci Marmont Shoulder Bag',
    brand: 'Gucci',
    description: 'Matelasse chevron leather with the iconic double G hardware. A modern classic.',
    price: 2350,
    images: ['/images/products/gucci-marmont.jpg'],
    category: 'Shoulder Bags',
    condition: 'Excellent',
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Prada Galleria Saffiano',
    brand: 'Prada',
    description: 'Structured saffiano leather tote with signature triangle logo. Professional elegance.',
    price: 2800,
    salePrice: 2400,
    images: ['/images/products/prada-galleria.jpg'],
    category: 'Totes',
    condition: 'Like New',
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Neverfull MM Damier',
    brand: 'Louis Vuitton',
    description: 'Versatile tote in Damier Ebene canvas. Perfect for work or travel.',
    price: 1800,
    images: ['/images/products/lv-neverfull.jpg'],
    category: 'Totes',
    condition: 'Excellent',
    inStock: true,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Boy Bag Medium',
    brand: 'Chanel',
    description: 'Edgy meets elegant. Quilted calfskin with brushed gold hardware.',
    price: 6500,
    images: ['/images/products/chanel-boy.jpg'],
    category: 'Shoulder Bags',
    condition: 'Like New',
    inStock: true,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const adminUsers: { email: string; password: string; name: string }[] = [
  { email: 'jan@bellabags.com', password: 'BBOB123!', name: 'Jan Ferraro' },
  { email: 'jessica@bellabags.com', password: 'BBOB123!', name: 'Jessica Cushing' },
];

export const categories = [
  'All',
  'Handbags',
  'Shoulder Bags',
  'Totes',
  'Crossbody',
  'Clutches',
  'Wallets',
];

export const brands = [
  'All',
  'Chanel',
  'Louis Vuitton',
  'Hermes',
  'Dior',
  'Gucci',
  'Prada',
  'Fendi',
  'Balenciaga',
  'Bottega Veneta',
  'Saint Laurent',
];

export const conditions = [
  'All',
  'New',
  'Like New',
  'Excellent',
  'Good',
  'Fair',
];
